# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Luana Brasil
subtitle: Desenvolvimento, besteiras e tudo que há de bom
description: Blog sobre minha jornada no mundo do desenvolvimento. Tutoriais e comentários sobre meus aprendizados e trabalhos. Inicialmente focado em Inteligência Artifical, porém vamos ver o que vem por aí, não dá pra saber ainda.
baseurl: "" 
# the subpath of your site, e.g. /blog
url: "" 
# the base hostname & protocol for your site, e.g. http://example.com
author_logo: profile.png
disqus_shortname: luanabrasil #for comments using disqus
author: Luana Brasil
author_bio: Estudante do último semestre de Ciência da Computação. Amante de videogames, música e reality shows de besteira
author_email: "luana_brasil@hotmail.com"
author_location: Fortaleza, CE - Brasil

# social links

github_username: cielthekid
linkedin_username: luanabrasil
telegram_username: cielthekid

# Build settings
markdown: kramdown
theme: devlopr
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
